/**
 * Multiple Sequence Alignment phylogeny module interface header file.
 * @author Rodrigo Siqueira <rodriados@gmail.com>
 * @copyright 2019-2020 Rodrigo Siqueira
 */
#pragma once

#include <phylogeny/phylogeny.cuh>

namespace msa
{
    /**
     * Represents the reference for an OTU. This reference may be used to address
     * both a single sequence as well as any multiple sequence alignment.
     * @since 0.1.1
     */
    typedef phylogeny::oturef oturef;

    /**
     * Represents the pseudo-phylogenetic tree generated by the phylogeny step.
     * This tree's nodes are addressed by OTUs references.
     * @since 0.1.1
     */
    typedef phylogeny::tree phylotree;
}
